In [2]:
import numpy as np

In [13]:
a = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
print (a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [15]:
type (a)

numpy.ndarray

In [16]:
a.size

10

In [17]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [19]:
a_centered = a - a_mean
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [26]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp


8.0

In [28]:
N = len(a)
N

5

In [29]:
c = a_centered_sp / (N - 1)
c

2.0