In [1]:
import numpy as np

In [3]:
#Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

a = np.arange (12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [46]:
#Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1
np.reshape (a, [2, 6])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
np.reshape (a, [6, 2])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [24]:
np.reshape (a, [3, 4])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
np.reshape (a, [4, 3])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [43]:
np.reshape (a, [12, 1])

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [47]:
#Создать 5 двумерных массивов разной формы из массива a. 
#Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк
np.reshape (a, [-1, 2])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [48]:
np.reshape (a, [-1, 4])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
np.reshape (a, [-1, 3])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [50]:
np.reshape (a, [6, -1])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [51]:
np.reshape (a, [4, -1])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
#Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

#НЕТ

In [53]:
#Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
#со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
#Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив
a = np.random.randn(3, 4)
a

array([[-0.87675409, -0.60763087,  0.24145269, -1.38419829],
       [ 0.42607609, -0.51001644, -0.50828033,  1.30183676],
       [-1.38135929, -0.26904837,  0.65350996,  1.17149901]])

In [54]:
a.size

12

In [56]:
c = a.flatten()
c

array([-0.87675409, -0.60763087,  0.24145269, -1.38419829,  0.42607609,
       -0.51001644, -0.50828033,  1.30183676, -1.38135929, -0.26904837,
        0.65350996,  1.17149901])

In [57]:
c.size

12

In [71]:
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2
a = np.arange (20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [74]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
#В чем разница между массивами a и b?
b = np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [85]:
#Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
#чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10
a = np.zeros((2, 2))
a.size

4

In [86]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [88]:
v = np.vstack((a, b))
v.size

10

In [92]:
#Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, 
#чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
#Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At 
#с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
a = np.arange (0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
A = np.reshape (a, [4, 3])
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [97]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [98]:
B.size

16

In [99]:
np.linalg.det(B)

0.0

In [101]:
#Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

np.random.seed(42)

In [102]:
#Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел 
#от 0 до 16 невключительно
a = np.arange(0, 16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [103]:
#Поменяйте его форму так, чтобы получилась квадратная матрица C. 
#Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, 
#умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.
C = a.reshape((4, 4))
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
D = 10 * C + B
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [105]:
np.linalg.det(D)

-7.685903354004529e-25

In [106]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 1.10382344e+13,  5.26315789e-02, -3.31147031e+13,
         2.20764688e+13],
       [-8.46264636e+13,  9.38249922e+13,  6.62294063e+13,
        -7.54279349e+13],
       [ 1.36138224e+14, -1.87649984e+14, -3.31147031e+13,
         8.46264636e+13],
       [-6.25499948e+13,  9.38249922e+13,  0.00000000e+00,
        -3.12749974e+13]])

In [108]:
#Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
#Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv 
#в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
#Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу 
#матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, 
#должны быть равны соответствующему элементу матрицы C
positive = D_inv > 0
negative = D_inv < 0

In [109]:
D_inv[positive] = 1
D_inv[negative] = 0
D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [110]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,   2,  32],
       [  4,  50,  86,   7],
       [ 23,   9,  10, 212],
       [ 12, 122,  14,  15]])